function [ emg1 , emg2 , emg3 , emg4 , emg5 , emg6 , emg7 , emg8 ] = function_acquisition( FileName , handles ) % Directory_MyoCapture, FileName,
    
    %Read Directories
    run( 'ReadDirectories.m' );
    %---

    while 1
        %UNTITLED2 Summary of this function goes here
        %   Detailed explanation goes here

        %% Import data from text file.
        % Script for importing data from the following text file:
        %
        %    C:\Users\Kevin\Documents\GitHub\myo_rehab\GUI\15KG_1.csv
        %
        % To extend the code to different selected data or a different text file,
        % generate a function instead of a script.

        % Auto-generated by MATLAB on 2016/05/19 06:41:39

        %% Initialize variables.
        PathInterractiveFile = strcat( Directory_MyoCapture , '\' , FileName );
        delimiter = ',';
        startRow = 2;
        Pause = 0.1; %If we want time between updates, uncomment this
        % variable and edit code just before 'drawnow update'

        %% Format string for each line of text:
        %   column1: double (%d)
        %	column2: double (%d)
        %   column3: double (%d)
        %	column4: double (%d)
        %   column5: double (%d)
        %	column6: double (%d)
        %   column7: double (%d)
        %	column8: double (%d)
        %   column9: double (%d)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%d%d%d%d%d%d%d%d%d%[^\n\r]';

        %% Open the text file.
        fileID = fopen(PathInterractiveFile,'r');

        %% Read columns of data according to format string.
        % This call is based on the structure of the file used to generate this
        % code. If an error occurs for a different file, try regenerating the code
        % from the Import Tool.
        dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

        %% Close the text file.
        fclose(fileID);

        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post
        % processing code is included. To generate code which works for
        % unimportable data, select unimportable cells in a file and regenerate the
        % script.

        %% Create output variable
        
        % Plot all the signals eveery 0.5 sec. (Change 'Pause' Variable to
        % change time for updates.
        emg = table(dataArray{1:end-1}, 'VariableNames', {'timestamp','emg1','emg2','emg3','emg4','emg5','emg6','emg7','emg8'});
       
            % Show the time and the number of samples in textBoxs
            Length = height(emg);
            Time = Length / 200; %200 Hz
            
            set(handles.txtTime,'string',Time);
            set(handles.txtLength,'string',Length);
            %-----
            
        % x definition
        x_axe = 1 : Length;
        
        % y definition for each graph
        emg1 = table2array(emg(:,2));
        emg2 = table2array(emg(:,3));
        emg3 = table2array(emg(:,4));
        emg4 = table2array(emg(:,5));
        emg5 = table2array(emg(:,6));
        emg6 = table2array(emg(:,7));
        emg7 = table2array(emg(:,8));
        emg8 = table2array(emg(:,9));
        
        % Plot signals
        axes(handles.plotInterEmg1);
        plot(x_axe,emg1,'r');
        axes(handles.plotInterEmg2);
        plot(x_axe,emg2,'r');
        axes(handles.plotInterEmg3);
        plot(x_axe,emg3,'r');
        axes(handles.plotInterEmg4);
        plot(x_axe,emg4,'r');
        axes(handles.plotInterEmg5);
        plot(x_axe,emg5,'r');
        axes(handles.plotInterEmg6);
        plot(x_axe,emg6,'r');
        axes(handles.plotInterEmg7);
        plot(x_axe,emg7,'r');
        axes(handles.plotInterEmg8);
        plot(x_axe,emg8,'r');
        
        pause(Pause);
        drawnow update
        %-----
        
% Just a try to see updates
%         axes(handles.plotInterEmg1);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg2);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg3);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg4);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg5);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg6);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg7);
%         plot(x_axe,0,'r');
%         axes(handles.plotInterEmg8);
%         plot(x_axe,0,'r');
%         
%         pause(0.0001);
%-----

        %% Clear temporary variables
        clearvars PathInterractiveFile delimiter startRow formatSpec fileID dataArray ans;
        
% Try to break the game!
%         if handles.acquisition == 0
%             break;
%         end
    end

end

